In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Importing and removing the thouands seperator

df = pd.read_csv('/content/Vehicle Data raw.csv', thousands= ',')

In [ ]:
# Sortaning / Renaming Column Names - Standaried State Names

df = df.rename(columns= {'Electric (EV)' : "EV" , 'Plug-In Hybrid Electric (PHEV)'  : 'PHEV' ,
                                  'Hybrid Electric (HEV)' : 'HEV' , 'Ethanol/Flex (E85)' : 'E85' ,
                                  'Compressed Natural Gas (CNG)' : 'CNG'
                                 })

In [ ]:
# Calculate the percentage of EVs, PHEVs, HEVs, and Gasoline vehicles for each state.

df['Total Vehicles'] = (df['EV'] + df['PHEV'] + df['HEV'] + df['Biodiesel'] + df['E85']  +
                        df['CNG'] + df['Propane'] + df['Hydrogen'] + df['Methanol'] + df['Gasoline'] + df['Diesel'] + df['Unknown Fuel'])

df['% of EV'] = df['EV']  / df['Total Vehicles'] * 100
df['% of PHEVs'] = df['PHEV']  / df['Total Vehicles'] * 100
df['% of HEVs'] = df['HEV']  / df['Total Vehicles'] * 100
df['% of Gasoline'] = df['Gasoline']  / df['Total Vehicles'] * 100

In [ ]:
# Identify the top 5 states with the highest EV adoption rate (EVs as a % of all registered vehicles).

df[['State', 'Total Vehicles' ,'% of EV']].sort_values('% of EV' , ascending = False).head()

                   State  Total Vehicles   % of EV
4             California        36850300  3.410013
8   District of Columbia          312100  2.595322
11                Hawaii         1080100  2.370151
47            Washington         6816100  2.231481
28                Nevada         2556100  1.854388

In [ ]:
# Compare EV adoption in California vs. other large states (e.g., Texas, Florida, New York).

condition = df['State'].isin(['California','Texas' ,'Florida', 'New York'])

df[['State', 'Total Vehicles' ,'% of EV']].loc[condition].sort_values('% of EV', ascending = False)

         State  Total Vehicles   % of EV
4   California        36850300  3.410013
9      Florida        18583200  1.371669
32    New York        11318600  1.160037
43       Texas        25796600  0.891978

In [ ]:
# Highlight which alternative fuels (biodiesel, ethanol, hydrogen) have meaningful presence vs. niche usage.

target_fuels = ['Biodiesel', 'E85', 'Hydrogen']
total_target_fules = df[target_fuels].sum()
total_vehicles = df['Total Vehicles'].sum()

percent = (total_target_fules / total_vehicles) * 100

niche_vs_broad = pd.DataFrame({
    'Total Fules' : total_target_fules,
    'percent' : percent
})

niche_vs_broad['presence'] = niche_vs_broad['percent'].apply(lambda x : "Meaningful" if x > 1.0 else "Niche")

niche_vs_broad

           Total Fules   percent    presence
Biodiesel      2803600  0.976536       Niche
E85           20240600  7.050103  Meaningful
Hydrogen         16900  0.005887       Niche

,State,EV,Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel,total_vehicles
0,Alabama,13000,5800,63300,54200,441200,100,100,0,0,4102200,127000,29000,4835900
1,Alaska,2700,900,10600,9600,46800,0,0,0,0,454300,29800,5100,559800
2,Arizona,89800,25600,175700,68600,437100,600,700,0,0,5469000,197700,64200,6529000
3,Arkansas,7100,3200,37000,37000,276700,200,0,0,0,2246100,90700,10300,2708300
4,California,1256600,410700,1703200,201600,1314600,10100,1500,16900,0,31191900,735300,7900,36850300
5,Colorado,90100,37500,152700,68100,334300,300,100,0,0,4508800,203400,46500,5441800
6,Connecticut,31600,18400,75300,10900,133600,100,0,0,0,2612600,42300,20900,2945700
7,Delaware,8400,3800,22900,5100,63900,0,0,0,0,791300,14200,5100,914700
8,District of Columbia,8100,3700,18100,400,16800,100,0,0,0,262500,1800,600,312100
9,Florida,254900,57300,414500,170500,1101100,400,100,0,0,16136500,351800,96100,18583200
10,Georgia,92400,22700,175300,92500,719400,300,200,0,0,8256400,206300,76900,9642400
11,Hawaii,25600,7300,36400,3400,37300,0,0,0,0,951000,15400,3700,1080100
12,Idaho,8500,4600,43700,45900,132900,100,100,0,0,1568600,138600,31600,1974600
13,Illinois,99600,33400,285400,61500,772900,300,0,0,0,8560300,170200,59600,10043200
14,Indiana,26100,12900,119100,56300,576300,300,0,0,0,5166200,156400,58500,6172100
15,Iowa,9000,6100,57200,41700,331300,100,0,0,0,2545400,105000,57500,3153300
16,Kansas,11300,5600,50400,27900,253500,200,100,0,0,2168600,87400,16100,2621100
17,Kentucky,11600,5600,67100,36900,361200,300,0,0,0,3415000,117600,24400,4039700
18,Louisiana,8200,4000,40200,64200,380100,100,0,0,0,3142800,115500,19100,3774200
19,Maine,7400,7600,33600,12000,104500,0,0,0,0,1036100,26900,7900,1236000
20,Maryland,72100,31300,168700,32100,309300,300,0,0,0,4327800,86900,31500,5060000
21,Massachusetts,73800,43800,187300,21300,285000,200,0,0,0,4791300,58400,30000,5491100
22,Michigan,50300,29100,148100,70400,873700,300,0,0,0,7129600,174500,49400,8525400
23,Minnesota,37100,16100,124500,52700,516400,100,0,0,0,4219200,127900,24500,5118500
24,Mississippi,3600,2000,28200,34900,295200,100,0,0,0,2275600,75200,8500,2723300
25,Missouri,26900,13900,113900,70400,575500,900,100,0,0,4608600,178200,37600,5626000
26,Montana,4600,2500,21100,37900,94500,0,0,0,0,780700,69600,10800,1021700
27,Nebraska,6900,3800,32600,28900,197100,100,0,0,0,1600400,76100,25300,1971200
28,Nevada,47400,10600,69600,27200,125600,200,100,0,0,2169300,85800,20300,2556100
29,New Hampshire,9900,6600,36800,13900,89600,100,0,0,0,1185300,29200,12300,1383700
30,New Jersey,134800,40900,174200,27800,392100,300,0,0,0,6433000,84600,36400,7324100
31,New Mexico,10300,4900,44300,32100,151600,100,100,0,0,1597600,88500,22900,1952400
32,New York,131300,92300,314000,54300,591100,400,100,0,0,9905500,150500,79100,11318600
33,North Carolina,70200,23700,210600,80200,655000,300,100,0,0,7764000,209700,71700,9085500
34,North Dakota,1000,800,8200,20400,89900,0,0,0,0,625300,44600,7200,797400
35,Ohio,50400,24000,199800,70300,833500,700,100,0,0,8881400,196200,60900,10317300
36,Oklahoma,22800,33000,56400,63100,352400,1800,200,0,0,3567500,145700,45000,4287900
37,Oregon,64400,28800,156900,55500,184600,100,100,0,0,3074300,217000,51000,3832700
38,Pennsylvania,70200,38900,245400,73900,661700,500,100,0,0,8886400,192100,41800,10211000
39,Rhode Island,6400,5100,22100,3100,41900,0,0,0,0,782000,11000,6000,877600
40,South Carolina,20900,9000,83100,44600,404600,100,100,0,0,4325000,110100,44900,5042400
41,South Dakota,1700,1300,11900,21500,98800,0,0,0,0,718300,51200,13300,918000
42,Tennessee,33200,11000,113300,53100,509000,200,100,0,0,5620500,160700,37700,6538800
43,Texas,230100,55300,445100,460700,2315400,1300,1300,0,0,21392800,772800,121800,25796600
44,Utah,40000,13000,83200,68500,185200,2200,500,0,0,2499600,158000,26000,3076200
45,Vermont,7800,5700,20300,7000,36600,0,0,0,0,496000,14700,5000,593100
46,Virginia,84900,26800,229400,44300,484800,300,0,0,0,6670000,152800,30200,7723500
47,Washington,152100,41200,307200,73800,337700,100,100,0,0,5583000,274200,46700,6816100
48,West Virginia,2800,1800,22400,17300,123400,100,0,0,0,1281500,46400,15200,1510900
49,Wisconsin,24900,12500,123600,52900,536200,300,0,0,0,4604700,147500,26400,5529000
50,Wyoming,1100,800,8400,21200,57700,0,0,0,0,489100,60900,13700,652900